name: Deploy Rails App to Cloud Run

on:
  push:
    branches:
      # - development
      - feature/#28
  workflow_dispatch:
    inputs:
      logLevel:
        required: true
        default: 'warning'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/flight_checker_api

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy flight-checker-backend --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/flight_checker_api --platform managed
